apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-application
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: myapp
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/username/repo-name.git
    targetRevision: HEAD
    path: path/to/manifest/
  project: default
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
  info:
    - name: description
      value: "This is my ArgoCD-managed app."
