apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-application
  namespace: argocd
spec:
  destination:
    namespace: myapp
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/Obiana-Ifeanyi/argo-gitops.git
    targetRevision: HEAD
    path: path/to/manifest/ # change this
  project: default
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
  info:
    - name: description
      value: "This is my ArgoCD-managed app."
