apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-app
  namespace: argocd
spec:
  destination:
    namespace: nginx
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/Obiana-Ifeanyi/argo-gitops.git
    targetRevision: HEAD # main  # Or the branch you want to track
    path: nginx  # Path to your Kubernetes manifests in the repo
  project: default
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
  info:
    - name: description
      value: "This is my ArgoCD-managed app."
