apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-index-page
  namespace: nginx
data:
  index.html: |
    <html>
    <head><title>Welcome to Nginx!</title></head>
    <body>
      <h1>Hello from Kubernetes Nginx!</h1>
    </body>
    </html>
